version: "3.9"
services:

  postgres_db:
    container_name: letspay_db
    image: postgres:15-alpine
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=paymentGateway
      - POSTGRES_USER=vertex
      - POSTGRES_PASSWORD=vertex123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vertex -p 5433 -d paymentGateway"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./misc:/misc # for transferring files like .sql imports
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: kickstart_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
