version: "3.9"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mynetwork

  postgres_db:
    container_name: kickstart_db
    image: postgres:15-alpine
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=kickstart
      - POSTGRES_USER=vertex
      - POSTGRES_PASSWORD=vertex123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vertex -p 5433 -d kickstart"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./misc:/misc # for transferring files like .sql imports
    networks:
      - mynetwork

  kickstart_redis_cache:
    image: redis:6.2-alpine
    container_name: kickstart_redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - mynetwork

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: kickstart_asynqmon
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=kickstart_redis_cache:6379
      - REDIS_DB=0
      - REDIS_PASSWORD= # if your Redis requires a password, set it here
      - ENABLE_METRICS_EXPORTER=true
    networks:
      - mynetwork
    depends_on:
      - kickstart_redis_cache

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
