version: "3.9"
services:

  postgres_db:
    container_name: letspay_db
    image: postgres:15-alpine
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=paymentGateway
      - POSTGRES_USER=vertex
      - POSTGRES_PASSWORD=vertex123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vertex -p 5433 -d paymentGateway"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./misc:/misc # for transferring files like .sql imports
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
